### ISSUE TITLE
The type initializer for 'PerTypeValues`1' threw an exception. 

### ISSUE THREAD

**Issue by AnudeepGarge** [dbolin/Apex.Serialization#112]
Hi,
While deserializing byte array I was throws "The type initializer for 'PerTypeValues`1' threw an exception. "
InnerException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I have referenced System.Runtime.CompilerServices.Unsafe nuget, but it did not help.

**Comment by dbolin** [comment]
What version of Apex.Serialization are you referencing, and what is the target framework for the consumer project?

This is a more general problem you can run into with .NET and library dependencies, it's not a problem with this package specifically.  There can be a variety of causes, so it might be more productive to do some research on it and see if you can find any of the common reasons for this, e.g. another dependency using a different version that what this package requires (sometimes this will be a build error, but sometimes not).

**Comment by AnudeepGarge** [comment]
I was using Dotnet 4.6.2 and facing this issue while running component tests. I solved this issue by adding right version of System.Runtime.CompilerServices.Unsafe to Gac.

**Comment by AnudeepGarge** [comment]
This issue is solved now. Thank you

**Comment by GuyG-Saha** [comment]
Can anybody share a solution for this issue please? what is Gac?

**Comment by fgasnier71** [comment]
GAC is Global Assembly Cache : it is there so that your applications can share some assemblies or even different versions of some assemblies.
