### ISSUE TITLE
Question: why is this repo 2.0.1 but the nuget package 3.x?

### ISSUE THREAD

**Issue by vpopescu** [dbolin/Apex.Serialization#132]
Just looking for a clarification, to make sure the nuget package is representative of the code here.

**Library Version Used & .NET Runtime Version**: 
NET 5

**Steps to Reproduce**:

Nuget package: https://www.nuget.org/packages/Apex.Serialization/3.0.0

**Expected Behavior**:
Same version on the repo and nuget package.

**Actual Behavior**:
Not same version on the repo and nuget package.

**Comment by dbolin** [comment]
Thanks for pointing this out - the releases on github are manually tagged so I simply forgot to do that when I pushed 3.0.0 to nuget.

**Comment by dbolin** [comment]
I've updated the releases here.
