### ISSUE TITLE
Comparison to other fast Serializer: Ceras

### ISSUE THREAD

**Issue by jogibear9988** [dbolin/Apex.Serialization#18]
I also found this one:
https://github.com/rikimaru0345/Ceras

maybe you could include a comparison? I'd like to change our's and I'm still searching wich one I use

**Comment by dbolin** [comment]
Sure, I can add that one to the comparisons and I'll see if I can add a more complex benchmark as well.

More important than performance is to be sure that the serializer fits your use case - for example this serializer is only intended to be used by a single application binary and only deserializing trusted data.  So it wouldn't be a good fit for the common client-server setup where the client app is on a machine you don't own, even if the application is yours.  The Readme has more details on other restrictions as well.

**Comment by dbolin** [comment]
I've updated the [Pocos](BenchmarkCases/Poco.md) benchmark to include Ceras, and added another one that serializes a single large object graph, which is more similar to my actual usage: [Large object graph](BenchmarkCases/LargeGraph.md)

**Comment by dbolin** [comment]
@jogibear9988 Are the above comparisons enough for you or do you have an idea for something more specific you'd like to see?  You should test your specific cases as well, since performance characteristics vary a lot case by case.

**Comment by jogibear9988** [comment]
top, thanks for it!
