### ISSUE TITLE
Does not work when underlying stream does not return full blocks at once

### ISSUE THREAD

**Issue by Titas22** [dbolin/Apex.Serialization#91]
Hi, 
I have run into some issues when combining Apex.Serialization and LZ4 compression.

**Library Version Used & .NET Runtime Version**: 
.NET Framework 4.7.1
Apex.Serialization v1.3.3

**Steps to Reproduce**:
1. Get lz4net and K4os.Compression.Streams Nuget packages (and Apex.Serialization of course)
2. Run the example code: [Example.txt](https://github.com/dbolin/Apex.Serialization/files/4884045/Example.txt)

**Expected Behavior**:
It should work

**Actual Behavior**:
It does not works and throws an error: 
```
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Apex.Serialization.Internal.BufferedStream.Flush()
   at Apex.Serialization.Read_APG.SimResults(Closure , BufferedStream& , Binary`1 )
   at Apex.Serialization.Binary`1.ReadSealedInternal[T]()
   at Apex.Serialization.Binary`1.ReadObjectEntry[T]()
   at Apex.Serialization.Binary`1.Read[T](Stream inputStream)
```
I though it was related to the LZ4 compression I was using and raised and issue with them but they explained that Apex.Serialization does not handle some cases correctly:

> https://github.com/MiloszKrajewski/K4os.Compression.LZ4/issues/36 :
>
> You can raise an issue of Apex.Serialization saying it does not work when underlying stream does not return full blocks at once (like network stream).
> 
> https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netcore-3.1
> 
> Note: "Returns: The total number of bytes read into the buffer. This can be less than the number of bytes allocated in the buffer if that many bytes are not currently available, or zero (0) if the end of the stream has been reached."
> 
> There is a lot of libraries which does not handle this case correctly.
> 
> In the meantime you can use K4os.Compression.Streams 1.2.2-beta which changed default behaviour (and blocks until full block is read).

Thanks,
Titas

**Comment by dbolin** [comment]
Thanks for the report - this should be fixed in 1.3.4 and 2.0.1.  I did have tests for the case where a stream returns less than the requested number of bytes, but this revealed another case where it could go wrong.  Let me know when you are able to try the update and if it works for you.

**Comment by Titas22** [comment]
Thanks, I tried it just now - works perfectly :)

**Comment by dbolin** [comment]
Good to know.  I'll close this then.

**Comment by KDGundermann** [comment]
>  but this revealed another case where it could go wrong

Which is this other case?
I'm just trying to switch from BinaryFormatter to Apex, sending data over as NetworkStream,
